### ISSUE TITLE
dials_scratch build broken

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2328]
From a fresh bootstrap build on Ubuntu 18.04.2 LTS, after
```
libtbx.configure dials_scratch/
```
The build fails, where the relevant error message appears to be
```
In file included from /home/fcx32934/sw/cctbx/modules/dials_scratch/idy/algorithms/spot_prediction/reflection_predictor.cc:13:
/home/fcx32934/sw/cctbx/modules/dials_scratch/idy/algorithms/spot_prediction/reflection_predictor.h: In constructor 'dials::algorithms::StillsExperimentalReflectionPredictor::StillsExperimentalReflectionPredictor(boost::shared_ptr<dxtbx::model::BeamBase>, const dxtbx::model::Detector&, scitbx::mat3<double>, const cctbx::uctbx::unit_cell&, const cctbx::sgtbx::space_group_type&, const double&, const double&)':
/home/fcx32934/sw/cctbx/modules/dials_scratch/idy/algorithms/spot_prediction/reflection_predictor.h:40:43: error: no matching function for call to 'dials::algorithms::StillsDeltaPsiReflectionPredictor::StillsDeltaPsiReflectionPredictor(const boost::shared_ptr<dxtbx::model::BeamBase>&, const dxtbx::model::Detector&, scitbx::mat3<double>&, const cctbx::uctbx::unit_cell&, const cctbx::sgtbx::space_group_type&, const double&)'
   40 |         ci_predict_ray_(beam->get_s0(),mos) {}
      |                                           ^
In file included from /home/fcx32934/sw/cctbx/modules/dials_scratch/idy/algorithms/spot_prediction/reflection_predictor.h:19,
```

**Comment by dagewa** [comment]
Full log: 
[build.log](https://github.com/dials/dials/files/10529752/build.log)

**Comment by rjgildea** [comment]
`boost::shared_ptr` needs changing to `std::shared_ptr` c.f. https://github.com/dials/dials/pull/2310
