### ISSUE TITLE
reconsider singleton use in dials scaling

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1271]
They represent a hidden global state which can lead to problems when using DIALS outside of its command line utilities.

Commit 97af72716a29371f7708dbe9a57ef82ea75df67a enabled full regression builds on Microsoft Azure, and the initial build on master failed with https://dev.azure.com/dials-azure/dials/_build/results?buildId=93&view=logs&j=b07f8cec-a30f-5203-0e14-918dff4b3a29&t=491cffd4-9824-5d1b-4a84-0ee286de40e8&l=44

```
=================================== FAILURES ===================================
_____________________________ test_few_reflections _____________________________
[gw1] linux -- Python 3.6.10 /home/vsts/work/1/build/../conda_base/bin/python3.6

        # Get the input experiment lists and reflection tables.
        data_dir = dials_data("l_cysteine_dials_output")
        experiments = ExperimentList.from_file(data_dir / "11_integrated.expt")
        experiments.extend(ExperimentList.from_file(data_dir / "23_integrated.expt"))
        refls = "11_integrated.refl", "23_integrated.refl"
        reflections = [flex.reflection_table.from_file(data_dir / refl) for refl in refls]
    
        # Get and use the default parameters for dials.scale, suppressing HTML output.
        scale_params = scale.phil_scope.fetch(
            source=phil.parse("output.html=None")
        ).extract()
        # Does what it says on the tin.  Run scaling.
>       scaled_expt, scaled_refl = scale.run_scaling(scale_params, experiments, reflections)

/home/vsts/work/1/dials-checkout/algorithms/scaling/test_scale.py:796: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/vsts/work/1/modules/dials/command_line/scale.py:195: in run_scaling
    algorithm.run()
/home/vsts/work/1/modules/dials/util/observer.py:46: in notify
    self.notify(event)
/home/vsts/work/1/modules/dials/util/observer.py:68: in notify
    callback(self)
/home/vsts/work/1/modules/dials/algorithms/scaling/observers.py:196: in print_scaling_summary
    MergingStatisticsObserver().data["statistics"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dataset_statistics = 'result'

    def make_merging_statistics_summary(dataset_statistics):
        """Format merging statistics information into an output string."""
    
        # Here use a StringIO to get around excessive padding/whitespace.
        # Avoid using result.show as don't want redundancies printed.
        out = StringIO()
    
        # First make summary
        make_sub_header("Merging statistics", out=out)
>       dataset_statistics.overall.show_summary(out=out)
E       AttributeError: 'str' object has no attribute 'overall'

/home/vsts/work/1/modules/dials/report/analysis.py:194: AttributeError
------------------------------ Captured log call -------------------------------
WARNING  dials:multi_dataset_handling.py:168 Duplicate dataset ids found in different reflection tables. These will be treated as coming from separate datasets, and new dataset ids will be assigned for the whole dataset.
WARNING  dials:algorithm.py:294 Error encountered during merging statistics calculation:
                                The data in None are already merged.  Only unmerged (but scaled) data may be used in this program.
Traceback (most recent call last):
  File "/home/vsts/work/1/modules/dials/algorithms/scaling/scaling_library.py", line 413, in merging_stats_from_scaled_array
    cc_one_half_significance_level=0.01,
  File "/home/vsts/work/1/modules/cctbx_project/iotbx/merging_statistics.py", line 548, in __init__
    i_obs.info().label_string())
Sorry: The data in None are already merged.  Only unmerged (but scaled) data may be used in this program.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vsts/work/1/modules/dials/algorithms/scaling/algorithm.py", line 291, in calculate_merging_stats
    self.params.output.use_internal_variance,
  File "/home/vsts/work/1/modules/dials/algorithms/scaling/scaling_library.py", line 417, in merging_stats_from_scaled_array
    "Error encountered during merging statistics calculation:\n%s" % e
dials.algorithms.scaling.scaling_utilities.DialsMergingStatisticsError: Error encountered during merging statistics calculation:
The data in None are already merged.  Only unmerged (but scaled) data may be used in this program.
```

Some string ended up in a place where a data structure should be. The test passes in isolation:
```
pytest algorithms/scaling/test_scale.py::test_few_reflections --regression
```
but fails when run after this additional test:
```
pytest algorithms/scaling/test_observers.py::test_MergingStatisticsObserver algorithms/scaling/test_scale.py::test_few_reflections --regression
```
The critical line in the `MergingStatisticsObserver` test is https://github.com/dials/dials/blob/97af72716a29371f7708dbe9a57ef82ea75df67a/algorithms/scaling/test_observers.py#L282
where the `observer` is a singleton that is modified but not reset after the test. I can't help but think this would also apply if a program does two scaling calls during its process lifetime. It certainly would apply if a program does two independent scaling calls in two separate threads.

The observer object layout may need to be reconsidered, and if deemed useful then the singleton pattern should be replaced by some sort of thread-safe observer context that is created before the calls and torn down afterwards rather than retained as a global shared singleton.

**Comment by Anthchirp** [comment]
I've marked the test as `xfail`, so the command to reproduce the issue is now
```
pytest --runxfail --regression algorithms/scaling/test_observers.py::test_MergingStatisticsObserver algorithms/scaling/test_scale.py::test_few_reflections
```

**Comment by benjaminhwilliams** [comment]
@jbeilstenedmands, I don't know if you might now have time to look into this.  It would be helpful to address it as it causes the failure of a test I introduced that covers behaviour of `dials.scale` for small data sets.  If it looks tricky to tackle this, an alternative would be for me to re-write the test to circumvent the issue.  Let me know what you prefer.
