### PR TITLE
Dynamic masking

### PR DESCRIPTION
**Pull request by rjgildea**
Move dynamic masking and related code to dxtbx in order to avoid dxtbx -> dials dependency.

### CODE REVIEW

**Comment by Anthchirp** [comment]
After merging the dxtbx side one test is broken:
```
ImportError while importing test module '/home/travis/build_dials/modules/dials/test/command_line/test_generate_distortion_maps.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../base/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/command_line/test_generate_distortion_maps.py:9: in <module>
    from dxtbx.format.Format import Masker
E   ImportError: cannot import name Masker
=========================== short test summary info ============================
ERROR test/command_line/test_generate_distortion_maps.py
```

**Comment by Anthchirp** [comment]
failing test already failing on master, so merging this should strictly improve the situation
