### ISSUE TITLE
Can no longer open data integrated by `dials.ssx_integrate` in the image viewer

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2593]
This definitely used to work, because we used it to investigate #2535. However, today I see:

```
$ dials.image_viewer data_002/integrated_1.{expt,refl}
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = data_002/integrated_1.expt
  reflections = data_002/integrated_1.refl
}

Preparing experiments (1 / 2)
Preparing experiments (2 / 2)
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/image_viewer.py", line 213, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/image_viewer.py", line 209, in run
    show_image_viewer(params=params, reflections=reflections, experiments=experiments)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/image_viewer.py", line 174, in show_image_viewer
    wrapper.display(experiments=experiments, reflections=reflections)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/image_viewer/spotfinder_wrap.py", line 86, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/image_viewer/spotfinder_frame.py", line 758, in load_image
    super().load_image(
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/image_viewer/slip_viewer/frame.py", line 508, in load_image
    self.update_settings()
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/image_viewer/spotfinder_frame.py", line 1299, in update_settings
    spotfinder_data = self.get_spotfinder_data()
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/image_viewer/spotfinder_frame.py", line 1986, in get_spotfinder_data
    refl_data = self._reflection_overlay_data(i_frame)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/image_viewer/spotfinder_frame.py", line 1897, in _reflection_overlay_data
    scan = expt_list[idx].scan.get_array_range()
AttributeError: Please report this error to dials-support@lists.sourceforge.net: 'NoneType' object has no attribute 'get_array_range'
```
Admittedly, this is not the same data set as I was looking at previously, so possibly there is something different here

**Comment by dagewa** [comment]
The line where it fails was last touched in https://github.com/dials/dials/pull/2556

**Comment by dagewa** [comment]
Looking at this with @jbeilstenedmands, the culprit appears to be the use of
```
dials.sequence_to_stills refined.expt refined.refl
```
in my workflow to convert a discrete tilt series into separate stills for processing with `dials.ssx_integrate`. This step loses the scan objects that otherwise are now retained by the SSX tools. While this does not cause the `dials.ssx_integrate` step to fail, it does mean that the fixes to the image viewer in #2556 no longer work for this kind of data.

One approach would be merely to fix the image viewer to work in this case, but I'm not totally happy that the form of the files output by `dials.ssx_integrate` (i.e. scanless experiments) for this use case is no longer the same form as output with standard SSX processing. So, an additional fix may be to introduce an option in `dials.sequence_to_stills` that converts scan sequences to stills sequences (retaining scan objects).
