### ISSUE TITLE
dials.symmetry crash when change_of_basis_ops_to_minimum_cell() cannot identify consistent cb_ops to minimum cell

### ISSUE THREAD

**Issue by huwjenkins** [dials/dials#2355]
Split from #2320 as this applies to `dials.symmetry` rather than `dials.cosym`. 

With the data from @biochem-fan in #2320 data `dials.symmetry` crashes:

```
$ dials.symmetry debug/*.{expt,refl}

...
Performing Laue group analysis

Couldn't match unit cell to target symmetry:
Unit cell: (5.51243, 9.81613, 29.6533, 95.7798, 94.0438, 103.934)
Space group: P 1 (No. 1)
Target symmetry: C 1 2/m 1
Traceback (most recent call last):
  File "/Users/huw/dials-dev/build/../modules/dials/src/dials/command_line/symmetry.py", line 588, in <module>
    run()
  File "/Users/huw/dials-dev/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/huw/dials-dev/build/../modules/dials/src/dials/command_line/symmetry.py", line 582, in run
    symmetry(experiments, reflections, params=params)
  File "/Users/huw/dials-dev/build/../modules/dials/src/dials/command_line/symmetry.py", line 336, in symmetry
    experiments, reflection_tables = apply_change_of_basis_ops(
  File "/Users/huw/dials-dev/build/../modules/dials/src/dials/command_line/symmetry.py", line 248, in apply_change_of_basis_ops
    refl["miller_index"] = cb_op_inp_min.apply(refl["miller_index"])
AttributeError: Please report this error to dials-support@lists.sourceforge.net: 'NoneType' object has no attribute 'apply'

```

This is because the change introduced in https://github.com/dials/dials/commit/d91bd0b8b7b25fd169cd4dc704e327db9882b696 here:

```diff
-        cb_ops = [cb_op_ref_min * cb_op for cb_op in cb_ops]
+        cb_ops = [cb_op_ref_min * cb_op if cb_op else None for cb_op in cb_ops]
```

requires changes like those made to `dials.cosym` in: https://github.com/dials/dials/commit/d91bd0b8b7b25fd169cd4dc704e327db9882b696 to filter out the offending experiments  to be added to `dials.symmetry` or a user friendly error message indicating the problematic dataset(s) to remove from the input.
