### ISSUE TITLE
XFEL cosym tests failing

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#1729]
Git bisect tells me they were broken by #1693, 05ac7be95c605956b220998e7e3549db9ea8f687.

I don't know why the dials xfel_regression didn't catch this (it appears xfel_regression [isn't running](https://dev.azure.com/azure-dials/dials/_build/results?buildId=3893&view=logs&jobId=0d58e9a6-523b-53c3-8fec-8582d58dc23e&j=0d58e9a6-523b-53c3-8fec-8582d58dc23e&t=b00761c1-fbcf-5bdd-d505-0bf7276ebc27) on the most recent commit?), but once #1693 was merged, the cctbx_project xfel_regression [began failing](https://dev.azure.com/cctbx/3d754415-9516-43fb-8e21-e1fae873ee5e/_apis/build/builds/14380/logs/77).  

Test output:
```
$ libtbx.python `libtbx.find_in_repositories xfel_regression`/test/util/tst_TargetWithFastRij.py"
Traceback (most recent call last):
  File "../modules/xfel_regression/test/util/tst_TargetWithFastRij.py", line 52, in <module>
    test_rij_wij_computer().run()
  File "../modules/xfel_regression/test/util/tst_TargetWithFastRij.py", line 31, in run
    rij_test, wij_test = test_instance._compute_rij_wij()
  File "/dev/shm/aaron/modules/cctbx_project/xfel/merging/application/modify/aux_cosym.py", line 244, in _compute_rij_wij
    LL,UU = self._lattice_lower_upper_index(lidx)
AttributeError: 'TargetWithFastRij' object has no attribute '_lattice_lower_upper_index'
```

**Comment by Anthchirp** [comment]
> I don't know why the dials xfel_regression didn't catch this (it appears xfel_regression isn't running on the most recent commit?)

We don't run x_r on commits, only on pull request builds. In this particular instance, the pull request build would have run x_r tests, but the [pull request was merged before the test had a chance to run](https://dev.azure.com/azure-dials/dials/_build/results?buildId=3855&view=logs&j=d6976828-e975-5272-b729-5dba29558695&t=eeb5b892-0477-589b-66d5-6cbc34bb87e0).
This is the [second time this week](https://github.com/dials/dials/pull/1699#issuecomment-847388092) that quickly merging PRs caused us issues :slightly_frowning_face:. I think we should discuss status checks before merging. I'll add this to the next core meeting agenda.

**Comment by Anthchirp** [comment]
Looks like you depended on a private method that was used for an inefficient algorithm and has now been removed. 

I suppose you could copy the implementation into your class (https://github.com/dials/dials/pull/1693/commits/c8aac49c3fc2815652ac3c211de60b34c6d44497) until you can update your algorithm accordingly?

**Comment by phyy-nx** [comment]
I've disabled the two tests temporarily.  We'll circle back early next week.

**Comment by dwpaley** [comment]
This should be fixed by these two commits: https://gitlab.com/cctbx/xfel_regression/-/commit/c726d516b5c01e0609d8ab42a7e81a16fa134c95 and https://github.com/cctbx/cctbx_project/commit/955d97d680c0d9f20a6be410aeb041d014c56bda

@rjgildea @ndevenish I noticed the new implementation of `compute_rij_wij()` will put 1s and 2s in the wij matrix even though we don't compute the corresponding rij's.

The tests pass locally so I'll close this issue and keep an eye on the Azure run.
